Goodbye Heroku, hello Railway
BattlesnakeOfficial/docs pull request #25
Opened 2022-12-11 18:58 UTC by ItsGoldeneyes

Now that Heroku's free tier is gone, Railway has become my go-to recommendation to new users.

Removed Heroku - Free tier is no more, don't think it warrants a recommendation anymore.

Replaced with Railway - Similar system to Heroku, free tier is great, developer tier is free for majority of snakes, just needs credit card to prevent fraud. Very helpful support channels in Discord, easy to get started for people who are new to hosting. Would put it above DigitalOcean if they weren't partnered with BattleSnake

2022-12-11 19:10 UTC, bvanvugt commented
Let's keep Heroku listed, but updated to reflect the new pricing. Otherwise looks good!

2022-12-11 19:19 UTC, ItsGoldeneyes commented
Let's leave Heroku out, there are some better free options on the page already. Going through the repo now and removing mentions of Heroku

2022-12-11 20:33 UTC, ItsGoldeneyes commented
Totally misread your message, thought you said to leave Heroku out, not untouched. I'll fix it

2022-12-11 20:43 UTC, ItsGoldeneyes commented
Fixed it, my mistake

2022-12-12 15:50 UTC, bvanvugt requested changes

2022-12-12 15:50 UTC, bvanvugt commented on docs/guides/tips/engine-regions.md
> +* Railway is hosted entirely on GCP US-WEST. use the "AWS US-WEST-2" region.
Small typo, 'use' vs. 'Use'

2022-12-31 22:21 UTC, bvanvugt approved these changes

2022-12-31 22:23 UTC, merged